
name: bzoing
version: '0.2'
summary: Simple calendar alarms for your desktop
description: |
  Bzoing provides a simple way to create task reminder alarms on your desktop
  using Python and Gtk3.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  bzoing:
    command: desktop-launch $SNAP/bin/bzoing-now
    plugs: [x11, unity7, alsa]

parts:
  bzoing:
    source: https://github.com/lapisdecor/bzoing.git
    # See 'snapcraft plugins'
    plugin: python
    stage-packages:
       - libnotify-bin
       - portaudio19-dev
       - python3-pyaudio
       - python3-gi
       - gir1.2-gtk-3.0
       - gir1.2-appindicator3-0.1
       - alsa-base
       - alsa-utils
       - libasound2
       - libasound2-data
       - libasound2-plugins
    after: [desktop-gtk3]
