
name: bzoing
base: core22
version: 'master'
summary: Simple calendar alarms for your desktop
description: |
  Bzoing provides a simple way to create task reminder alarms on your desktop
  using Python and Gtk3.
architectures:
  - amd64
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots


parts:
  bzoing:
    source: https://github.com/lapisdecor/bzoing.git
    source-type: git
    plugin: python
    stage-packages:
      - xdg-user-dirs
      - python3-xdg
      - pulseaudio-utils
      - libayatana-appindicator3-1
      - libnotify-bin
      - libcanberra-gtk3-module
    

apps:
  bzoing:
    extensions: [gnome]
    command: bin/bzoing-now
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
    plugs:
      - unity7
      - pulseaudio
